
package App;


public class App extends javax.swing.JFrame {

  
    public App() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rbBird = new javax.swing.JRadioButton();
        rbCat = new javax.swing.JRadioButton();
        rbDog = new javax.swing.JRadioButton();
        rbRabbit = new javax.swing.JRadioButton();
        rbPig = new javax.swing.JRadioButton();
        lblImage = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selecting  Pet");

        buttonGroup1.add(rbBird);
        rbBird.setText("Bird");
        rbBird.setToolTipText("");
        rbBird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBirdActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCat);
        rbCat.setText("Cat");
        rbCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCatActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbDog);
        rbDog.setText("Dog");
        rbDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDogActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbRabbit);
        rbRabbit.setText("Rabbit");
        rbRabbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRabbitActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPig);
        rbPig.setText("Pig");
        rbPig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbDog)
                    .addComponent(rbRabbit)
                    .addComponent(rbPig)
                    .addComponent(rbCat)
                    .addComponent(rbBird))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbBird)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbCat)
                .addGap(22, 22, 22)
                .addComponent(rbDog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbRabbit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbPig)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbBirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBirdActionPerformed
        lblImage.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/Images/bird.png.jpeg")));

        javax.swing.JOptionPane.showMessageDialog(
        this,
        "You selected: Bird");      
    }//GEN-LAST:event_rbBirdActionPerformed

    private void rbCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCatActionPerformed
         lblImage.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/Images/cat.png.jpeg")));

        javax.swing.JOptionPane.showMessageDialog(
        this,
        "You selected: Cat"); 
    }//GEN-LAST:event_rbCatActionPerformed

    private void rbDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDogActionPerformed
         lblImage.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/Images/dog.png.jpeg")));

        javax.swing.JOptionPane.showMessageDialog(
        this,
        "You selected: Dog"); 
    }//GEN-LAST:event_rbDogActionPerformed

    private void rbRabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRabbitActionPerformed
         lblImage.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/Images/rabbit.png.jpeg")));

        javax.swing.JOptionPane.showMessageDialog(
        this,
        "You selected: Rabbit"); 
    }//GEN-LAST:event_rbRabbitActionPerformed

    private void rbPigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPigActionPerformed
         lblImage.setIcon(new javax.swing.ImageIcon(
        getClass().getResource("/Images/pig.png.jpeg")));

        javax.swing.JOptionPane.showMessageDialog(
        this,
        "You selected: Pig"); 
    }//GEN-LAST:event_rbPigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JRadioButton rbBird;
    private javax.swing.JRadioButton rbCat;
    private javax.swing.JRadioButton rbDog;
    private javax.swing.JRadioButton rbPig;
    private javax.swing.JRadioButton rbRabbit;
    // End of variables declaration//GEN-END:variables
}
